name: release

on:
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and publish
        run: ./gradlew clean build publishMods
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
